[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++17

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
  -std=gnu++17
